// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShippingMark.Data;

namespace ShippingMark.Data.SPMigrations
{
    [DbContext(typeof(ShippingContext))]
    partial class ShippingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("ShippingMark.Models.CartonLabel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .HasColumnType("TEXT");

                    b.Property<int>("BuyerCartonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CartonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CartonQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Col0")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Col00")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Col1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Col10")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Col12")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Col14")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Col16")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Col18")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Col2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Col20")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Col22")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Col24")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Col26")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Col28")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Col3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Col30")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Col4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Col5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Col6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Col8")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fab")
                        .HasColumnType("TEXT");

                    b.Property<int>("StylePPJ")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalGrossWeight")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalNetWeight")
                        .HasColumnType("REAL");

                    b.Property<int>("TotalPieces")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("CartonLabels");
                });
#pragma warning restore 612, 618
        }
    }
}
